### ISSUE TITLE
consider to generate `sass variables` format.

### ISSUE THREAD

**Issue by notzheng** [primer/primitives#494]
For now,  primitive data is served in several formats:
- `dist/scss`
- `dist/json`
- `dist/js`

But in `dist/scss`, it has only  mixins with all color CSS variables and make the bundle size is large. But in some scene (maybe just mine probably...) , only some colors are needed, but have to import them all.

So, wouldn't is better to generate an `sass variables` format like this?

```scss
// _dark.vars.scss

$canvas-default: #0d1117;
$fg-default: #c9d1d9;
// more....
```

usage:

```scss
@use "@primer/primitives/dist/scss/colors/_dark.vars" as dark;

:root {
  --color-canvas-default: dark.$canvas-default;
}

.box {
  color: dark.$fg-default;
}
```

---

In my case, I wrote a script to generate the `vars.scss` files base on json format.  this issue is just a feature request.
